# Configure main menu and social menu

[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[main.params]
    icon = "home"
#newtab = true

[[main]]
identifier = "professional experience"
name = "Professional Experience"
url = "/categories/professional experience/"
weight = 2
[main.params]
    icon = "archives"

[[main]]
identifier = "projects"
name = "Projects"
url = "/categories/projects/"
weight = 3
[main.params]
    icon = "archives"


[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/CaiJimmy/hugo-theme-stack"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com"

    [social.params]
        icon = "brand-twitter"
